@reg copy HKLM\HARDWARE\ACPI\DSDT\VBOX__ HKLM\HARDWARE\ACPI\DSDT\DELL__ /s /f
@reg delete HKLM\HARDWARE\ACPI\DSDT\VBOX__ /f
@reg copy HKLM\HARDWARE\ACPI\RSDT\VBOX__  HKLM\HARDWARE\ACPI\RSDT\DELL__ /s /f
@reg delete HKLM\HARDWARE\ACPI\RSDT\VBOX__ /f
@reg copy HKLM\HARDWARE\ACPI\FADT\VBOX__ HKLM\HARDWARE\ACPI\FADT\DELL__ /s /f
@reg delete HKLM\HARDWARE\ACPI\FADT\VBOX__ /f
 
 
@reg copy HKEY_LOCAL_MACHINE\HARDWARE\ACPI\DSDT\DELL__\VBOXBIOS HKEY_LOCAL_MACHINE\HARDWARE\ACPI\DSDT\DELL__\DELLBIOS /s /f
 
 
@reg delete HKEY_LOCAL_MACHINE\HARDWARE\ACPI\DSDT\DELL__\VBOXBIOS /f
 
 
@reg copy HKEY_LOCAL_MACHINE\HARDWARE\ACPI\FADT\DELL__\VBOXFACP HKEY_LOCAL_MACHINE\HARDWARE\ACPI\FADT\DELL__\DELLFACP /s /f
 
 
@reg delete HKEY_LOCAL_MACHINE\HARDWARE\ACPI\FADT\DELL__\VBOXFACP /f
 
 
@reg copy HKEY_LOCAL_MACHINE\HARDWARE\ACPI\RSDT\DELL__\VBOXXSDT HKEY_LOCAL_MACHINE\HARDWARE\ACPI\RSDT\DELL__\DELLRSDT /s /f
 
 
@reg delete HKEY_LOCAL_MACHINE\HARDWARE\ACPI\RSDT\DELL__\VBOXXSDT /f
 
 
@reg add HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SystemInformation /t REG_SZ /v BIOS /d DELL /f
 
@reg add HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SystemInformation /t REG_SZ /v BIOSVersion /d DELL /f
 
@reg add HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SystemInformation /t REG_SZ /v SystemProductName /d DELL /f
 
@reg add HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\SystemInformation /t REG_SZ /v SystemManufacturer /d DELL /f 
  
@reg add HKEY_LOCAL_MACHINE\HARDWARE\DESCRIPTION\System /v SystemBiosVersion /t REG_MULTI_SZ /d "DELL -1" /f
  
@reg add HKEY_LOCAL_MACHINE\HARDWARE\DESCRIPTION\System /v VideoBiosVersion /t REG_MULTI_SZ /d "VGA BIOS v1.54" /f
